@echo off

set CLUSTER_DIR=%WORK_DIR%\cluster
set CONTAINER1_DIR=%CLUSTER_DIR%\instance1
set CONTAINER2_DIR=%CLUSTER_DIR%\instance2
set CONTAINER3_DIR=%CLUSTER_DIR%\instance3
set CONTAINER4_DIR=%CLUSTER_DIR%\instance4
set CONTAINER5_DIR=%CLUSTER_DIR%\instance5
set CONTAINER6_DIR=%CLUSTER_DIR%\instance6

set CLUSTER_PATH=%VOLUME_PATH%/cluster
set CONTAINER1_PATH=%CLUSTER_PATH%/instance1
set CONTAINER2_PATH=%CLUSTER_PATH%/instance2
set CONTAINER3_PATH=%CLUSTER_PATH%/instance3
set CONTAINER4_PATH=%CLUSTER_PATH%/instance4
set CONTAINER5_PATH=%CLUSTER_PATH%/instance5
set CONTAINER6_PATH=%CLUSTER_PATH%/instance6

set INSTANCE_BASE_NAME=redis-instance
set CONTAINER1_NAME=%INSTANCE_BASE_NAME%1
set CONTAINER2_NAME=%INSTANCE_BASE_NAME%2
set CONTAINER3_NAME=%INSTANCE_BASE_NAME%3
set CONTAINER4_NAME=%INSTANCE_BASE_NAME%4
set CONTAINER5_NAME=%INSTANCE_BASE_NAME%5
set CONTAINER6_NAME=%INSTANCE_BASE_NAME%6

set IP_ADDRESS_BASE=192.168.50.10

exit /b 0
