@echo off

set MASTER_CONTAINER_NAME=redis-instance1
set SLAVE1_CONTAINER_NAME=redis-instance2
set SLAVE2_CONTAINER_NAME=redis-instance3
set SENTINEL1_CONTAINER_NAME=redis-sentinel1
set SENTINEL2_CONTAINER_NAME=redis-sentinel2
set SENTINEL3_CONTAINER_NAME=redis-sentinel3

set SENTINEL_DIR=%WORK_DIR%\sentinel
set MASTER_DIR=%SENTINEL_DIR%\%MASTER_CONTAINER_NAME%
set SLAVE1_DIR=%SENTINEL_DIR%\%SLAVE1_CONTAINER_NAME%
set SLAVE2_DIR=%SENTINEL_DIR%\%SLAVE2_CONTAINER_NAME%
set SENTINEL1_DIR=%SENTINEL_DIR%\%SENTINEL1_CONTAINER_NAME%
set SENTINEL2_DIR=%SENTINEL_DIR%\%SENTINEL2_CONTAINER_NAME%
set SENTINEL3_DIR=%SENTINEL_DIR%\%SENTINEL3_CONTAINER_NAME%

set SENTINEL_PATH=%VOLUME_PATH%/sentinel
set MASTER_PATH=%SENTINEL_PATH%/%MASTER_CONTAINER_NAME%
set SLAVE1_PATH=%SENTINEL_PATH%/%SLAVE1_CONTAINER_NAME%
set SLAVE2_PATH=%SENTINEL_PATH%/%SLAVE2_CONTAINER_NAME%
set SENTINEL1_PATH=%SENTINEL_PATH%/%SENTINEL1_CONTAINER_NAME%
set SENTINEL2_PATH=%SENTINEL_PATH%/%SENTINEL2_CONTAINER_NAME%
set SENTINEL3_PATH=%SENTINEL_PATH%/%SENTINEL3_CONTAINER_NAME%

exit /b 0

:RUN_CONTAINER
    set VOLUME_DIR=%1
    set VOLUME_PATH=%2
    set ORG_CONFIG=%3
    set CONTAINER_NAME=%4
    set EXECUTABLE=%5
    
    mkdir %VOLUME_DIR%
    copy /y %ORG_CONFIG% %VOLUME_DIR%\redis.conf
    docker run ^
        -d ^
        --rm ^
        --name %CONTAINER_NAME% ^
        --net %DOCKER_NETWORK% ^
        -v %VOLUME_PATH%/redis.conf:%REDIS_CONFIG% ^
        %REDIS_IMAGE% ^
        %EXECUTABLE% %REDIS_CONFIG%
exit /b 0

